# Generated by Django 5.2 on 2025-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
