# Generated by Django 5.2 on 2025-06-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
